version: 2

before:
  hooks:
    - helm package charts/karpenter-provider-huawei --destination .

builds:
  - id: karpenter-provider-huawei
    main: ./cmd/controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives: []

release:
  discussion_category_name: General
  draft: true
  extra_files:
    - glob: './karpenter-provider-huawei-*.tgz'
