apiVersion: v2
name: karpenter-provider-huawei
description: Huawei Cloud provider for Karpenter - Kubernetes Node Autoscaling
type: application
version: 0.3.2
appVersion: "0.3.2"
keywords:
  - karpenter
  - autoscaling
  - huawei
  - cloud
  - kubernetes
home: https://github.com/HuaweiCloudDeveloper/karpenter-provider-huawei
sources:
  - https://github.com/HuaweiCloudDeveloper/karpenter-provider-huawei
